version: "3"
volumes:
  pgdata:
services:
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    image: node:12
    container_name: app
    command: bash -c "npm run start:dev"
    restart: always
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app:cached
    depends_on:
      - postgres
    ports:
      - 3000:3000
